import './globals.css'
import Home from './page'

export const metadata = {
  title: 'SW blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <>
    <Home />
    {/* {title} */}

    {/* {body} */}

    {/* {nav} */}
   </>
  )
}
